'use strict'

// ******************************** 布局对象 ********************************

const Layout = {
  // properties
  manager: $('#workspace-page-manager'),
  items: null,
  heads: null,
  layouts: null,
  layout: null,
  default: null,
  dragging: null,
  resizing: null,
  focusableSelector: null,
  focusableElements: null,
  // methods
  initialize: null,
  switchLayout: null,
  createGroups: null,
  updateGroups: null,
  updateGroupTabs: null,
  updateGroupInfo: null,
  mergeGroups: null,
  setGroupSize: null,
  computeSizesBefore: null,
  computeSizesAfter: null,
  updateHint: null,
  getKeyGroups: null,
  getGroupOfElement: null,
  readyToFocus: null,
  createGroupContent: null,
  createGroupBorder: null,
  enableFocusableElements: null,
  disableFocusableElements: null,
  saveNavStates: null,
  saveLayoutScheme: null,
  loadLayoutScheme: null,
  saveToConfig: null,
  loadFromConfig: null,
  // events
  windowResize: null,
  windowLocalize: null,
  pageSwitch: null,
  navWrite: null,
  navPointerdown: null,
  navDragstart: null,
  navDragend: null,
  navDragenter: null,
  navDragleave: null,
  navDragover: null,
  navDrop: null,
  regionDragleave: null,
  regionDragover: null,
  borderPointerdown: null,
  pointerup: null,
  pointermove: null,
}

export { Layout }
