'use strict'

// ******************************** 检查器 ********************************

const Inspector = {
  // properties
  manager: null,
  type: null,
  meta: null,
  fileScene: null,
  fileUI: null,
  fileAnimation: null,
  fileParticle: null,
  fileTileset: null,
  fileActor: null,
  fileSkill: null,
  fileTrigger: null,
  fileItem: null,
  fileEquipment: null,
  fileState: null,
  fileEvent: null,
  fileImage: null,
  fileAudio: null,
  fileVideo: null,
  fileFont: null,
  fileScript: null,
  sceneActor: null,
  sceneRegion: null,
  sceneLight: null,
  sceneAnimation: null,
  sceneParticle: null,
  sceneParallax: null,
  sceneTilemap: null,
  uiElement: null,
  uiImage: null,
  uiText: null,
  uiTextBox: null,
  uiDialogBox: null,
  uiProgressBar: null,
  uiVideo: null,
  uiWindow: null,
  uiContainer: null,
  animMotion: null,
  animJointLayer: null,
  animJointFrame: null,
  animSpriteLayer: null,
  animSpriteFrame: null,
  animParticleLayer: null,
  animParticleFrame: null,
  particleLayer: null,
  // methods
  initialize: null,
  open: null,
  close: null,
  getKey: null,
  // events
  inspectorResize: null,
  managerKeydown: null,
  scrollPointerdown: null,
  inputFocus: null,
  inputBlur: null,
  sliderFocus: null,
  sliderBlur: null,
  // classes
  ParamHistory: null,
}

export { Inspector }
