'use strict'

// ******************************** 属性窗口 ********************************

const Attribute = {
  // properties
  list: $('#attribute-list'),
  panel: $('#attribute-properties-flex').hide(),
  searcher: $('#attribute-searcher'),
  inputs: {
    name: $('#attribute-name'),
    key: $('#attribute-key'),
    type: $('#attribute-type'),
    note: $('#attribute-note'),
    enum: $('#attribute-enum'),
    enumBox: $('#attribute-enum-box'),
  },
  mode: null,
  target: null,
  data: null,
  idList: null,
  settings: null,
  settingKeys: null,
  history: null,
  changed: false,
  // methods
  initialize: null,
  open: null,
  undo: null,
  redo: null,
  createId: null,
  getItemById: null,
  setFolderGroup: null,
  getGroup: null,
  getGroupAttribute: null,
  getDefAttributeId: null,
  getAttributeItems: null,
  openPropertyPanel: null,
  closePropertyPanel: null,
  unpackAttribute: null,
  packAttribute: null,
  saveHistory: null,
  // events
  windowClose: null,
  windowClosed: null,
  keydown: null,
  listKeydown: null,
  listPointerdown: null,
  listDoubleclick: null,
  listSelect: null,
  listRecord: null,
  listOpen: null,
  listPopup: null,
  nameInput: null,
  keyInput: null,
  typeWrite: null,
  typeInput: null,
  enumInput: null,
  noteInput: null,
  panelKeydown: null,
  searcherInput: null,
  confirm: null,
  apply: null,
}

export { Attribute }
