'use strict'

// ******************************** 指令对象 ********************************

const Command = {
  // properties
  target: null,
  id: null,
  words: null,
  format: false,
  invalid: false,
  // methods
  initialize: null,
  insert: null,
  edit: null,
  open: null,
  save: null,
  parse: null,
  parseBlend: null,
  parseVariable: null,
  parseGlobalVariable: null,
  parseAttributeKey: null,
  parseVariableTag: null,
  parseVariableNumber: null,
  parseVariableString: null,
  parseVariableEnum: null,
  parseVariableFile: null,
  parseMultiLineString: null,
  parseSpriteName: null,
  parseEventType: null,
  parseEnumString: null,
  parseGroupEnumString: null,
  parseListItem: null,
  parseParameter: null,
  parseActor: null,
  parseSkill: null,
  parseState: null,
  parseEquipment: null,
  parseItem: null,
  parseRegion: null,
  parsePosition: null,
  parseAngle: null,
  parseDegrees: null,
  parseTrigger: null,
  parseLight: null,
  parseElement: null,
  parsePresetObject: null,
  parsePresetElement: null,
  parseTeam: null,
  parseActorSelector: null,
  parseFileName: null,
  parseAudioType: null,
  parseWait: null,
  parseEasing: null,
  parseUnlinkedId: null,
  parseObjectName: null,
  // classes
  WordList: null,
  FormatUpdater: null,
  // objects
  cases: {},
  custom: null,
}

export { Command }
